apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo02"
  description: "demo02"
  tags:
    - sx-cnp-oss
    - template
    - metalstack
  links:
    - url: https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at
      title: Grafana SRE Metrics
      icon: web
  annotations:
    github.com/project-slug: phac008/demo02
    backstage.io/kubernetes-id: demo02
    kubecost.com/deployment-name: demo02
    argocd/app-name: demo02
    argocd/app-namespace: adn-sx-cnp-oss
    backstage.io/kubernetes-namespace: sx-cnp-oss-demo02
    backstage.io/kubernetes-label-selector: app=demo02
    kubevirt-manager: "https://kubevirt-manager.lab.suxessit.k8s.cloud.uibk.ac.at/"
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "(tags @> 'kubevirt')"
    grafana/overview-dashboard: "https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=&var-namespace=qa-demo-kubevirt&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: qa
  owner: "sx-cnp-oss"
  system: demo02
  dependsOn:
    - resource:argocd
    - resource:kubevirt
    - resource:kubecost
    - resource:k8s-monitoring
    - resource:kubevirt-manager
    - resource:kubevirt
    - resource:loki
