# prod
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "podtato-head-option-5-prod"
  description: "podtato-head-option-5-prod"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://podtato-head-option-5-prod.demo.kubrix.cloud/
      title: Prod Instance of podtato-head-option-5
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/team-1-podtato-head-option-5
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=podtato-head-option-5-prod'
    argocd/app-selector: 'app.kubernetes.io/instance=podtato-head-option-5-prod'
    argocd/app-namespace: adn-team-1
    #argocd/app-name: podtato-head-option-5-prod
    argocd/project-name: team-1-project
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/team-1-podtato-head-option-5-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&from=now-1h&to=now&timezone=browser&var-datasource=default&var-cluster=kubrix-demo&var-namespace=team-1-podtato-head-option-5-prod&var-resolution=30s&var-created_by=$__all&refresh=30s"
spec:
  type: service
  lifecycle: prod
  owner: "kubrix"
  system: jokl-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: podtato-head-option-5
---
#qa
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "podtato-head-option-5-qa"
  description: "podtato-head-option-5-qa"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://podtato-head-option-5-qa.demo.kubrix.cloud
      title: QA Instance of podtato-head-option-5
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/team-1-podtato-head-option-5
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=podtato-head-option-5-qa'
    argocd/app-selector: 'app.kubernetes.io/instance=podtato-head-option-5-qa'
    argocd/app-namespace: adn-team-1
    #argocd/app-name: podtato-head-option-5-qa
    argocd/project-name: team-1-project
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/team-1-podtato-head-option-5-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&from=now-1h&to=now&timezone=browser&var-datasource=default&var-cluster=kubrix-demo&var-namespace=team-1-podtato-head-option-5-qa&var-resolution=30s&var-created_by=$__all&refresh=30s"
spec:
  type: service
  lifecycle: qa
  owner: "kubrix"
  system: jokl-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: podtato-head-option-5
---
# test
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "podtato-head-option-5-test"
  description: "podtato-head-option-5-test"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: http://podtato-head-option-5-test.demo.kubrix.cloud
      title: Test Instance of podtato-head-option-5
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/team-1-podtato-head-option-5
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=podtato-head-option-5-test'
    argocd/app-selector: 'app.kubernetes.io/instance=podtato-head-option-5-test'
    argocd/app-namespace: adn-team-1
    #argocd/app-name: podtato-head-option-5-test
    argocd/project-name: team-1-project
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/team-1-podtato-head-option-5-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.demo.kubrix.cloud/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&from=now-1h&to=now&timezone=browser&var-datasource=default&var-cluster=kubrix-demo&var-namespace=team-1-podtato-head-option-5-test&var-resolution=30s&var-created_by=$__all&refresh=30s"
spec:
  type: service
  lifecycle: test
  owner: "kubrix"
  system: jokl-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: podtato-head-option-5
---
# main, at the end of catalog-info.yaml so that register link is on main component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "podtato-head-option-5"
  description: "podtato-head-option-5"
  tags:
    - template
    - kargo
    - metalstack
    - kubrix
  links:
    - url: https://argocd.demo.kubrix.cloud/applications/adn-team-1/podtato-head-option-5?resource=
      title: ArgoCD Application Information of podtato-head-option-5
      icon: web
  annotations:
    github.com/project-slug: kubriX-demo/team-1-podtato-head-option-5
    backstage.io/kubernetes-label-selector:  'app.kubernetes.io/instance=podtato-head-option-5'
    argocd/app-namespace: adn-team-1
    #argocd/app-name: team-1-podtato-head-option-5
    argocd/app-selector: 'app.kubernetes.io/instance=podtato-head-option-5'
    argocd/project-name: team-1-project
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.demo.kubrix.cloud/project/team-1-podtato-head-option-5-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
spec:
  type: service
  lifecycle: experimental
  owner: "kubrix"
  system: jokl-app
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
---
